EXTENSIONS = {
    '.rb': 'ruby',
    '.go': 'go',
    '.rs': 'rust',
    '.java': 'java',
    '.js': 'javascript',
    '.ts': 'typescript',
    '.py': 'python',
    '.c': 'c',
    '.h': 'c',
    '.cpp': 'cpp',
    '.hpp': 'cpp',
    '.kt': 'kotlin',
    '.kts': 'kotlin',
    '.ktm': 'kotlin',
    '.php': 'php',
}